---
abstract: 'a generator for ABC Path puzzle games.'
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  Test::Differences: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3617'
keywords:
  - abc
  - game
  - games
  - generate
  - generator
  - grid
  - letters
  - path
  - puzzle
  - puzzles
  - riddle
  - riddles
  - table
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-ABC_Path-Generator
provides:
  Games::ABC_Path::Generator:
    file: lib/Games/ABC_Path/Generator.pm
    version: v0.0.1
  Games::ABC_Path::Generator::App:
    file: lib/Games/ABC_Path/Generator/App.pm
    version: v0.0.1
  Games::ABC_Path::Generator::Base:
    file: lib/Games/ABC_Path/Generator/Base.pm
    version: v0.0.1
  Games::ABC_Path::Generator::Constants:
    file: lib/Games/ABC_Path/Generator/Constants.pm
    version: v0.0.1
  Games::ABC_Path::Generator::FinalLayoutObj:
    file: lib/Games/ABC_Path/Generator/FinalLayoutObj.pm
    version: v0.0.1
  Games::ABC_Path::Generator::RiddleObj:
    file: lib/Games/ABC_Path/Generator/RiddleObj.pm
    version: v0.0.1
  Games::ABC_Path::MicrosoftRand:
    file: lib/Games/ABC_Path/MicrosoftRand.pm
    version: v0.0.1
requires:
  Carp: 0
  Class::XSAccessor: 0
  Exporter: 0
  Games::ABC_Path::Solver::Base: 0
  Games::ABC_Path::Solver::Board: 0.001000
  Getopt::Long: 2.36
  integer: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  homepage: http://www.shlomifish.org/open-source/projects/japanese-puzzle-games/abc-path/
  license: http://opensource.org/licenses/mit-license.php
  repository: http://svn.berlios.de/svnroot/repos/fc-solve/abc-path/
version: v0.0.1
